### ISSUE TITLE
Implement ext_ccc field

### ISSUE THREAD

**Issue by dbrgn** [coredump-ch/status#104]
In our case it should be `"ext_ccc": "chaostreff"`.

**Comment by dbrgn** [comment]
https://spaceapi.ccc.de/

**Comment by das-g** [comment]
Beschreibung hier: https://cpu.ccc.de/spaceapi-ccc-de/

**Comment by dbrgn** [comment]
Habe die URL auf https://spaceapi.ccc.de/list submitted.
