### ISSUE TITLE
Split up codebase into multiple repos

### ISSUE THREAD

**Issue by dns2utf8** [coredump-ch/status#70]
I would like to use the Types on the Client too.

**Comment by dns2utf8** [comment]
Suggesting `spaceapi_types` as the name.

**Comment by dbrgn** [comment]
This is a follow-up of #26.

**Comment by dbrgn** [comment]
As we're mostly finished with initial development now, we could indeed split up the codebase into separate repos that are published on crates.io.

The process to update something in the spaceapi module would then be:

1. Create a PR to the `spaceapi` crate
2. Merge the PR
3. Prepare a release
4. Update the version number in `Cargo.toml` of the server implementation
5. Release and deploy new version.

A bit more complex, but should allow us to work on the separate parts in parallel.

My suggestion for the crate and repo names:

- `spaceapi-types`
- `spaceapi-server`
- `spaceapi-coredump` (not published on crates.io)

For the release, I'd set the version everywhere to `0.1.0`, symbolizing the first (not yet stabilized) release.

@rnestler what do you think of this?

**Comment by dbrgn** [comment]
Also, people like @dns2utf8 can use the `spaceapi-types` crate to deserialize the api response.

**Comment by rnestler** [comment]
I wouldn't call it `spaceapi-types` but just `spaceapi-rs` or something the like. Because its not only the types but also serialisation/de-serialisation code.

**Comment by dbrgn** [comment]
In that case just `spaceapi`, if it's a package on crates.io it's obvious that it's written in Rust.

**Comment by rnestler** [comment]
Whats the convention in the rust community for repo names vs crate names? I had the impression that lots of github repo had the `-rs` suffix but the crates hadn't

**Comment by dbrgn** [comment]
We could do that. But do you think it adds any value?

**Comment by rnestler** [comment]
I think there are a lot of spaceapi repos on github which have nothing to do with rust.

**Comment by dbrgn** [comment]
Alright:

- `spaceapi` / `spaceapi-rs`
- `spaceapi-server` / `spaceapi-server-rs`
- `spaceapi-coredump-rs`

We could also call the last repo `coredump-status` instead.

**Comment by dbrgn** [comment]
All in favor?

**Comment by rnestler** [comment]
:+1:

**Comment by dbrgn** [comment]
Great. We first need to close #71, #72, #73 though.

**Comment by dbrgn** [comment]
Wohoo! First crate is live.

https://crates.io/crates/spaceapi
https://github.com/coredump-ch/spaceapi-rs

**Comment by rnestler** [comment]
Awesome! :smile: :sparkles:

**Comment by dns2utf8** [comment]
Thanks :+1:

**Comment by rnestler** [comment]
Should I start with the split of `spaceapi-server-rs`? @dbrgn could you give me some pointers on how to do it?

**Comment by dbrgn** [comment]
@rnestler I already started with that yesterday. What would help more would be to do review #77 and to take a look at #55.

**Comment by dbrgn** [comment]
Btw, this is how I did it: https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/

**Comment by dbrgn** [comment]
Wohoo!

https://crates.io/crates/spaceapi-server
https://github.com/coredump-ch/spaceapi-server-rs

**Comment by rnestler** [comment]
@dbrgn There is an issue with the link to the documentation on crates.io

**Comment by rnestler** [comment]
The documentation is at `spaceapi-server/spaceapi_server/index.html` but the link on crates.io points to `spaceapi-server/spaceapi-server/index.html`

**Comment by rnestler** [comment]
And on https://crates.io/crates/spaceapi there is no documentation link at all.

**Comment by dbrgn** [comment]
Hm, as far as I know there's no way to update crate information after it has been published.

Should we simply fix and publish 0.1.1 for both?

**Comment by rnestler** [comment]
I think the crates.io link is correct, since the crate is named spaceapi-server. But the documentation seems to be generated at the wrong place.

**Comment by dbrgn** [comment]
No, the package is called `spaceapi-server` but the crate is called `spaceapi_server`. It was just a mistake on my side.

I'll republish both.

**Comment by rnestler** [comment]
So the remaining thing is the rename of this repo. Proposals:
 * status
 * coredump-status
 * spaceapi-status
 * coredump-spaceapi-status
 * spaceapi-coredump
 * All of the above with a 'rs' suffix

**Comment by dbrgn** [comment]
I'm for `status` :)

**Comment by dbrgn** [comment]
spaceapi-server update is released. https://crates.io/crates/spaceapi-server
