### ISSUE TITLE
Time dependency

### ISSUE THREAD

**Issue by dbrgn** [coredump-ch/status#99]
Apparently the `time` dependency is deprecated.

Find out what the proper replacement is.

**Comment by dbrgn** [comment]
See https://dependencyci.com/github/coredump-ch/telegram-groups-bot/builds/1

**Comment by dns2utf8** [comment]
Did we migrate to [std::time](https://doc.rust-lang.org/stable/std/time/struct.Duration.html)?

**Comment by dbrgn** [comment]
Take a look at the linked issue. We didn't actually use `time` ourselves.

**Comment by dns2utf8** [comment]
ah, I see /me stupid. Sorry
